// GENERATED from the hardmaterials report corpus — do not edit by hand.
// Split: metadata only. Chapter body html lives in ./bodies/chNN.ts and is
// lazy-loaded through ./chapterBodies.ts.
export interface Section { anchor: string; level: number; title: string; html: string }
export interface SectionMeta { anchor: string; level: number; title: string }
export interface ChapterMeta { id: string; number: number; title: string; part: number; partName: string; wordCount: number; readingTime: number; sections: SectionMeta[] }
/** Back-compat alias: report code consumes metadata only. */
export type Chapter = ChapterMeta

export const chapters: ChapterMeta[] = [
 {
  "id": "ch01",
  "number": 1,
  "title": "Hard Materials, Honest Errors",
  "part": 1,
  "partName": "The Argument",
  "wordCount": 1543,
  "readingTime": 7,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "executive-summary", "level": 2, "title": "Executive Summary" },
   { "anchor": "1-1-1", "level": 4, "title": "1.1.1" },
   { "anchor": "1-2-1", "level": 4, "title": "1.2.1" },
   { "anchor": "1-2-2", "level": 4, "title": "1.2.2" },
   { "anchor": "1-3-1", "level": 4, "title": "1.3.1" },
   { "anchor": "1-3-2", "level": 4, "title": "1.3.2" },
   { "anchor": "1-4-1", "level": 4, "title": "1.4.1" },
  ]
 },
 {
  "id": "ch02",
  "number": 2,
  "title": "2. Introduction and Class-Selection Criteria",
  "part": 1,
  "partName": "The Argument",
  "wordCount": 2001,
  "readingTime": 9,
  "sections": [
   { "anchor": "s2-1", "level": 2, "title": "2.1 Why I am writing this" },
   { "anchor": "2-1-1", "level": 4, "title": "2.1.1" },
   { "anchor": "s2-2", "level": 2, "title": "2.2 The thesis in one paragraph" },
   { "anchor": "2-2-1", "level": 4, "title": "2.2.1" },
   { "anchor": "s2-3", "level": 2, "title": "2.3 Selection criteria for the nine classes" },
   { "anchor": "2-3-1", "level": 4, "title": "2.3.1" },
   { "anchor": "2-3-2", "level": 4, "title": "2.3.2" },
   { "anchor": "2-3-3", "level": 4, "title": "2.3.3" },
   { "anchor": "s2-4", "level": 2, "title": "2.4 Scope exclusions" },
   { "anchor": "2-4-1", "level": 4, "title": "2.4.1" },
   { "anchor": "s2-5", "level": 2, "title": "2.5 How to read this report" },
   { "anchor": "2-5-1", "level": 4, "title": "2.5.1" },
   { "anchor": "s2-6", "level": 2, "title": "2.6 Freshness and evidence standard" },
   { "anchor": "2-6-1", "level": 4, "title": "2.6.1" },
  ]
 },
 {
  "id": "ch03",
  "number": 3,
  "title": "3. Methods: The Error Landscape and the Correction Stack",
  "part": 2,
  "partName": "The Lens",
  "wordCount": 5000,
  "readingTime": 22,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s3-1", "level": 2, "title": "3.1 The inherited error floor" },
   { "anchor": "s3-1-1", "level": 3, "title": "3.1.1 Two-layer model: DFT systematic floors inherited by MLIPs" },
   { "anchor": "s3-2", "level": 2, "title": "3.2 A taxonomy of the errors that matter" },
   { "anchor": "s3-2-1", "level": 3, "title": "3.2.1 Nine error modes with physics origin, discovery consequence, one quantified emblem each" },
   { "anchor": "s3-3", "level": 2, "title": "3.3 The error-correction scoreboard" },
   { "anchor": "s3-3-1", "level": 3, "title": "3.3.1 Rows 1–5: data and model corrections that exist today" },
   { "anchor": "s3-3-2", "level": 3, "title": "3.3.2 Rows 6–10: the credibility layer and the hard residual" },
   { "anchor": "s3-4", "level": 2, "title": "3.4 The data levers" },
   { "anchor": "s3-5", "level": 2, "title": "3.5 Stability and synthesizability: the identify axis" },
   { "anchor": "s3-6", "level": 2, "title": "3.6 The credibility crisis and the validation economy" },
   { "anchor": "s3-7", "level": 2, "title": "3.7 How the class chapters use this lens" },
  ]
 },
 {
  "id": "ch04",
  "number": 4,
  "title": "4. Superconductors: Cuprates, Nickelates, and High-Pressure Hydrides",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2063,
  "readingTime": 9,
  "sections": [
   { "anchor": "s4-1", "level": 2, "title": "4.1 Why this class, why now" },
   { "anchor": "s4-2", "level": 2, "title": "4.2 The error landscape" },
   { "anchor": "s4-2-1", "level": 3, "title": "4.2.1 Cuprates: DFT fails qualitatively" },
   { "anchor": "s4-2-2", "level": 3, "title": "4.2.2 No ab initio Tc for unconventional superconductors" },
   { "anchor": "s4-2-3", "level": 3, "title": "4.2.3 Hydrides: harmonic DFT is quantitatively wrong" },
   { "anchor": "s4-2-4", "level": 3, "title": "4.2.4 MLIPs: inherited floors plus their own failure modes" },
   { "anchor": "s4-3", "level": 2, "title": "4.3 Where the correction lever is" },
   { "anchor": "s4-4", "level": 2, "title": "4.4 Counter-narrative" },
   { "anchor": "s4-5", "level": 2, "title": "4.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s4-6", "level": 2, "title": "4.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch05",
  "number": 5,
  "title": "5. Correlated Oxides and Quantum Materials",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2023,
  "readingTime": 9,
  "sections": [
   { "anchor": "s5-1", "level": 2, "title": "5.1 Why this class, why now" },
   { "anchor": "s5-1-1", "level": 4, "title": "5.1.1 Neuromorphic and quantum hardware run on oxide defect physics" },
   { "anchor": "s5-2", "level": 2, "title": "5.2 The error landscape" },
   { "anchor": "s5-2-1", "level": 4, "title": "5.2.1 Qualitative failure is structural, not a functional bug" },
   { "anchor": "s5-2-2", "level": 4, "title": "5.2.2 What best-practice correction still leaves behind" },
   { "anchor": "s5-2-3", "level": 4, "title": "5.2.3 The cost wall: the correct methods are not screening-capable" },
   { "anchor": "s5-2-4", "level": 4, "title": "5.2.4 Topology adds a binary failure mode" },
   { "anchor": "s5-2-5", "level": 4, "title": "5.2.5 MLIPs are spin-blind; the spin-aware frontier inherits the DFT+U ceiling" },
   { "anchor": "s5-3", "level": 2, "title": "5.3 Where the correction lever is" },
   { "anchor": "s5-4", "level": 2, "title": "5.4 Counter-narrative: the U-parameter is the class arguing with itself" },
   { "anchor": "s5-5", "level": 2, "title": "5.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s5-6", "level": 2, "title": "5.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch06",
  "number": 6,
  "title": "6. High-Entropy Alloys and Disorder",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2379,
  "readingTime": 10,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s6-1", "level": 2, "title": "6.1 Why this class, why now" },
   { "anchor": "s6-1-1", "level": 3, "title": "6.1.1 Value is proven; prediction is the bottleneck" },
   { "anchor": "s6-2", "level": 2, "title": "6.2 The error landscape" },
   { "anchor": "s6-2-1", "level": 3, "title": "6.2.1 MS25: five architectures cannot learn even a classical potential" },
   { "anchor": "s6-2-2", "level": 3, "title": "6.2.2 Foundation models collapse zero-shot; specialized potentials plateau" },
   { "anchor": "s6-2-3", "level": 3, "title": "6.2.3 The DFT side is not a refuge" },
   { "anchor": "s6-3", "level": 2, "title": "6.3 Where the correction lever is" },
   { "anchor": "s6-3-1", "level": 3, "title": "6.3.1 Equivariance, Δ-learning, and element-wise MoE" },
   { "anchor": "s6-4", "level": 2, "title": "6.4 Counter-narrative: the entropy premise failed, and the field knows it" },
   { "anchor": "s6-4-1", "level": 3, "title": "6.4.1 Hype-cycle telemetry, quantified" },
   { "anchor": "s6-5", "level": 2, "title": "6.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s6-5-1", "level": 3, "title": "6.5.1 Two supply-chain anxieties, one missing capability" },
   { "anchor": "s6-6", "level": 2, "title": "6.6 Bridge to the discovery chains" },
   { "anchor": "s6-6-1", "level": 3, "title": "6.6.1 Chain 4 and the venture bet" },
  ]
 },
 {
  "id": "ch07",
  "number": 7,
  "title": "7. Batteries",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2258,
  "readingTime": 10,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s7-1", "level": 2, "title": "7.1 Why this class, why now" },
   { "anchor": "s7-2", "level": 2, "title": "7.2 The error landscape" },
   { "anchor": "s7-2-1", "level": 3, "title": "7.2.1 Barriers: five models, one floor" },
   { "anchor": "s7-2-2", "level": 3, "title": "7.2.2 The asymmetry is the story" },
   { "anchor": "s7-2-3", "level": 3, "title": "7.2.3 Voltages inherit the functional floor" },
   { "anchor": "s7-2-4", "level": 3, "title": "7.2.4 Root cause, and one bright spot" },
   { "anchor": "s7-2-5", "level": 3, "title": "7.2.5 The rare-event regime" },
   { "anchor": "s7-3", "level": 2, "title": "7.3 Where the correction lever is" },
   { "anchor": "s7-4", "level": 2, "title": "7.4 Counter-narrative: timelines and trust" },
   { "anchor": "s7-5", "level": 2, "title": "7.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s7-6", "level": 2, "title": "7.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch08",
  "number": 8,
  "title": "8. Catalysts",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2155,
  "readingTime": 9,
  "sections": [
   { "anchor": "s8-1", "level": 2, "title": "8.1 Why this class, why now" },
   { "anchor": "s8-2", "level": 2, "title": "8.2 The error landscape" },
   { "anchor": "s8-2-1", "level": 3, "title": "8.2.1 The floor: twice measured against experiment" },
   { "anchor": "s8-2-2", "level": 3, "title": "8.2.2 The plateau: the label floor made visible" },
   { "anchor": "s8-2-3", "level": 3, "title": "8.2.3 Barriers and rates: the error Arrhenius amplifies" },
   { "anchor": "s8-2-4", "level": 3, "title": "8.2.4 Qualitative errors: when the error bar cannot save you" },
   { "anchor": "s8-2-5", "level": 3, "title": "8.2.5 Operando reality: the modeled catalyst is not the working catalyst" },
   { "anchor": "s8-3", "level": 2, "title": "8.3 Where the correction lever is" },
   { "anchor": "s8-4", "level": 2, "title": "8.4 The counter-narrative — endogenous, and correct" },
   { "anchor": "s8-5", "level": 2, "title": "8.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s8-6", "level": 2, "title": "8.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch09",
  "number": 9,
  "title": "9. Magnets and the REE-Free Problem",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2463,
  "readingTime": 11,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s9-1", "level": 2, "title": "9.1 Why this class, why now" },
   { "anchor": "s9-1-1", "level": 3, "title": "9.1.1 Two clocks and a price shock" },
   { "anchor": "s9-2", "level": 2, "title": "9.2 The error landscape" },
   { "anchor": "s9-2-1", "level": 3, "title": "9.2.1 $T_c$: the decoupling band" },
   { "anchor": "s9-2-2", "level": 3, "title": "9.2.2 Coercivity: Brown's paradox and the invisible microstructure" },
   { "anchor": "s9-2-3", "level": 3, "title": "9.2.3 Anisotropy and the 4$f$ problem" },
   { "anchor": "s9-2-4", "level": 3, "title": "9.2.4 MLIPs inherit — and amplify" },
   { "anchor": "s9-3", "level": 2, "title": "9.3 Where the correction lever is" },
   { "anchor": "s9-4", "level": 2, "title": "9.4 Counter-narrative: why substitution underdelivers" },
   { "anchor": "s9-5", "level": 2, "title": "9.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s9-6", "level": 2, "title": "9.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch10",
  "number": 10,
  "title": "10. Fusion and Nuclear Materials",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 3020,
  "readingTime": 13,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s10-1", "level": 2, "title": "10.1 Why this class, why now" },
   { "anchor": "s10-1-1", "level": 3, "title": "10.1.1 The program clock runs ahead of the materials clock" },
   { "anchor": "s10-2", "level": 2, "title": "10.2 The error landscape" },
   { "anchor": "s10-2-1", "level": 3, "title": "10.2.1 The multi-scale trap" },
   { "anchor": "s10-2-2", "level": 3, "title": "10.2.2 The validation gap" },
   { "anchor": "s10-2-3", "level": 3, "title": "10.2.3 The many-species data wall" },
   { "anchor": "s10-2-4", "level": 3, "title": "10.2.4 The tritium arithmetic" },
   { "anchor": "s10-3", "level": 2, "title": "10.3 Where the correction lever is" },
   { "anchor": "s10-4", "level": 2, "title": "10.4 Counter-narrative: the Jassby–Abdou position, at full strength" },
   { "anchor": "s10-5", "level": 2, "title": "10.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s10-6", "level": 2, "title": "10.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch11",
  "number": 11,
  "title": "11. Porous Frameworks and 2D Materials",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2218,
  "readingTime": 10,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s11-1", "level": 2, "title": "11.1 Why this class, why now" },
   { "anchor": "s11-1-1", "level": 3, "title": "11.1.1 One industrial proof, two policy pulls" },
   { "anchor": "s11-2", "level": 2, "title": "11.2 The error landscape" },
   { "anchor": "s11-2-1", "level": 3, "title": "11.2.1 Dispersion: a solved problem that keeps not being solved, scheme by scheme" },
   { "anchor": "s11-2-2", "level": 3, "title": "11.2.2 Framework energetics: non-systematic error is the worst kind" },
   { "anchor": "s11-2-3", "level": 3, "title": "11.2.3 MLIPs inherit the framework problem, then add a transfer problem" },
   { "anchor": "s11-2-4", "level": 3, "title": "11.2.4 The stability axis" },
   { "anchor": "s11-3", "level": 2, "title": "11.3 Where the correction lever is" },
   { "anchor": "s11-3-1", "level": 3, "title": "11.3.1 Dispersion-corrected MLIPs, and honest stability labels" },
   { "anchor": "s11-4", "level": 2, "title": "11.4 Counter-narrative: the field's own skepticism" },
   { "anchor": "s11-5", "level": 2, "title": "11.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s11-6", "level": 2, "title": "11.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch12",
  "number": 12,
  "title": "12. Wide-Bandgap Semiconductors, Perovskites, Thermoelectrics",
  "part": 3,
  "partName": "The Nine Classes",
  "wordCount": 2279,
  "readingTime": 10,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s12-1", "level": 2, "title": "12.1 Why this class, why now" },
   { "anchor": "s12-2", "level": 2, "title": "12.2 The error landscape" },
   { "anchor": "s12-2-1", "level": 3, "title": "12.2.1 Band gaps: a 50% systematic at the source, a factor-1.6 database downstream" },
   { "anchor": "s12-2-2", "level": 3, "title": "12.2.2 Error cancellation masquerading as accuracy" },
   { "anchor": "s12-2-3", "level": 3, "title": "12.2.3 Thermal and anharmonic terms: the 0.7 eV room-temperature correction" },
   { "anchor": "s12-2-4", "level": 3, "title": "12.2.4 MLIP status: softened phonons, unbound defect levels" },
   { "anchor": "s12-3", "level": 2, "title": "12.3 Where the correction lever is" },
   { "anchor": "s12-4", "level": 2, "title": "12.4 Counter-narrative" },
   { "anchor": "s12-5", "level": 2, "title": "12.5 Policy hooks: Beijing and Washington" },
   { "anchor": "s12-6", "level": 2, "title": "12.6 Bridge to the discovery chains" },
  ]
 },
 {
  "id": "ch13",
  "number": 13,
  "title": "13. The Master Meta-Review Matrix",
  "part": 4,
  "partName": "The Synthesis",
  "wordCount": 2088,
  "readingTime": 9,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s13-1", "level": 2, "title": "13.1 How to read the matrix" },
   { "anchor": "s13-2", "level": 2, "title": "13.2 The matrix" },
   { "anchor": "s13-3", "level": 2, "title": "13.3 Cross-class convergence: fixes that pay twice" },
   { "anchor": "s13-4", "level": 2, "title": "13.4 CN/US asymmetry columns" },
  ]
 },
 {
  "id": "ch14",
  "number": 14,
  "title": "14. Stability and Synthesizability: The Identify Axis",
  "part": 4,
  "partName": "The Synthesis",
  "wordCount": 1583,
  "readingTime": 7,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s14-1", "level": 2, "title": "14.1 The thesis: a crowded axis and an empty one" },
   { "anchor": "s14-2", "level": 2, "title": "14.2 Five flagship cases" },
   { "anchor": "s14-2-1", "level": 3, "title": "14.2.1 MOFs: thermodynamics disguised as stability" },
   { "anchor": "s14-2-2", "level": 3, "title": "14.2.2 MXenes: the two-week shelf life" },
   { "anchor": "s14-2-3", "level": 3, "title": "14.2.3 Perovskites: the warranty gates the class" },
   { "anchor": "s14-2-4", "level": 3, "title": "14.2.4 Tetrataenite: equilibrium blindness" },
   { "anchor": "s14-2-5", "level": 3, "title": "14.2.5 Operando catalysts: the candidate you screened is not the catalyst you run" },
   { "anchor": "s14-2-6", "level": 3, "title": "14.2.6 Reading the five together" },
   { "anchor": "s14-3", "level": 2, "title": "14.3 The stability-first doctrine" },
  ]
 },
 {
  "id": "ch15",
  "number": 15,
  "title": "15. Discovery Chains",
  "part": 4,
  "partName": "The Synthesis",
  "wordCount": 3376,
  "readingTime": 15,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s15-1", "level": 2, "title": "15.1 The grammar and its rules" },
   { "anchor": "s15-2", "level": 2, "title": "15.2 The chain cards" },
   { "anchor": "s15-2-1", "level": 3, "title": "15.2.1 Chain 1 — batteries: barrier-accurate MLIPs (readiness H)" },
   { "anchor": "s15-2-2", "level": 3, "title": "15.2.2 Chain 2 — magnets: spin-aware multi-fidelity MLIPs (readiness M)" },
   { "anchor": "s15-2-3", "level": 3, "title": "15.2.3 Chain 3 — catalysts: Δ-learned hybrid-accuracy screening with operando validation (readiness M)" },
   { "anchor": "s15-2-4", "level": 3, "title": "15.2.4 Chain 4 — high-entropy alloys: disorder-native MLIPs (readiness M)" },
   { "anchor": "s15-2-5", "level": 3, "title": "15.2.5 Chain 5 — porous frameworks: dispersion-corrected MLIPs (readiness M)" },
   { "anchor": "s15-2-6", "level": 3, "title": "15.2.6 Chain 6 — semiconductors and perovskites: an error-cancellation-free excited-state stack (readiness M)" },
   { "anchor": "s15-2-7", "level": 3, "title": "15.2.7 Chain 7 — fusion materials: rare-event-validated MLIPs with uncertainty quantification (readiness L)" },
   { "anchor": "s15-2-8", "level": 3, "title": "15.2.8 Chain 8 — superconductors: anharmonicity-aware MLIPs plus ML-DMFT (readiness L)" },
   { "anchor": "s15-2-9", "level": 3, "title": "15.2.9 Chain 9 — correlated oxides: correlation-aware MLIPs (readiness L)" },
   { "anchor": "s15-2-10", "level": 3, "title": "15.2.10 Chain 10 — the stability meta-chain: a stability-first discovery loop (readiness M)" },
   { "anchor": "s15-2-11", "level": 3, "title": "15.2.11 Chain 11 — thermoelectrics: anharmonicity-aware thermal-conductivity prediction (readiness L)" },
   { "anchor": "s15-3", "level": 2, "title": "15.3 Traceability" },
   { "anchor": "s15-3-1", "level": 3, "title": "15.3.1 Chain → class chapter → anchor error figure → policy gate; the conviction ranking" },
  ]
 },
 {
  "id": "ch16",
  "number": 16,
  "title": "16. China: Alignment with the 15th Five-Year Plan",
  "part": 5,
  "partName": "The Demand Side",
  "wordCount": 4040,
  "readingTime": 18,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s16-1", "level": 2, "title": "16.1 What the 15FYP prioritizes" },
   { "anchor": "s16-1-1", "level": 3, "title": "16.1.1 Architecture: two documents, six chokepoint domains, AI as organizing logic" },
   { "anchor": "s16-1-2", "level": 3, "title": "16.1.2 Macro targets that pull materials demand" },
   { "anchor": "s16-2", "level": 2, "title": "16.2 The mirror-image map" },
   { "anchor": "s16-3", "level": 2, "title": "16.3 Class-by-class alignment" },
   { "anchor": "s16-3-1", "level": 3, "title": "16.3.1 The verbatim list, quoted and mapped" },
   { "anchor": "s16-4", "level": 2, "title": "16.4 Instruments and on-ramps" },
   { "anchor": "s16-4-1", "level": 3, "title": "16.4.1 Money: national funds first, provincial stacks second" },
   { "anchor": "s16-4-2", "level": 3, "title": "16.4.2 Foreign-entity on-ramps, codified" },
   { "anchor": "s16-4-3", "level": 3, "title": "16.4.3 Compute and data: vouchers, the national platform layer, and the GPU constraint" },
   { "anchor": "s16-4-4", "level": 3, "title": "16.4.4 Demand pull: dated, concrete, and materials-gated" },
   { "anchor": "s16-5", "level": 2, "title": "16.5 Binding gates and risks" },
   { "anchor": "s16-5-1", "level": 3, "title": "16.5.1 The risk surface, stated factually" },
   { "anchor": "s16-5-2", "level": 3, "title": "16.5.2 My read: dual alignment is possible, and it is time-gated" },
  ]
 },
 {
  "id": "ch17",
  "number": 17,
  "title": "17. United States Alignment",
  "part": 5,
  "partName": "The Demand Side",
  "wordCount": 3356,
  "readingTime": 15,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s17-1", "level": 2, "title": "17.1 The demand signal" },
   { "anchor": "s17-1-1", "level": 4, "title": "17.1.1 The USGS Final 2025 List, read group by group" },
   { "anchor": "s17-2", "level": 2, "title": "17.2 The DOE reorganization and pipeline" },
   { "anchor": "s17-2-1", "level": 4, "title": "17.2.1 November 20, 2025: the re-sorted department" },
   { "anchor": "s17-2-2", "level": 4, "title": "17.2.2 The ~$1B CMEI critical-minerals pipeline, itemized" },
   { "anchor": "s17-2-3", "level": 4, "title": "17.2.3 The Genesis Mission: AI-for-science with a materials address" },
   { "anchor": "s17-3", "level": 2, "title": "17.3 Instruments for a solo founder" },
   { "anchor": "s17-3-1", "level": 4, "title": "17.3.1 SBIR/STTR: lapsed, reauthorized, and rebuilt" },
   { "anchor": "s17-3-2", "level": 4, "title": "17.3.2 Beyond SBIR: the independent-researcher stack" },
   { "anchor": "s17-4", "level": 2, "title": "17.4 Class-by-class alignment" },
   { "anchor": "s17-4-1", "level": 4, "title": "17.4.1 Nine classes, nine instrument matches" },
   { "anchor": "s17-5", "level": 2, "title": "17.5 The gates and the credibility bar" },
   { "anchor": "s17-5-1", "level": 4, "title": "17.5.1 Budget texture a program officer expects you to know" },
   { "anchor": "s17-5-2", "level": 4, "title": "17.5.2 My nearest gate, stated plainly" },
  ]
 },
 {
  "id": "ch18",
  "number": 18,
  "title": "18. Phased Roadmap",
  "part": 6,
  "partName": "The Program",
  "wordCount": 2330,
  "readingTime": 10,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s18-1", "level": 2, "title": "18.1 Phase one, 0–24 months" },
   { "anchor": "s18-1-1", "level": 3, "title": "18.1.1 Error-correction milestones: replicate, then validate, in public" },
   { "anchor": "s18-1-2", "level": 3, "title": "18.1.2 Funding and compute gates, ordered by friction" },
   { "anchor": "s18-2", "level": 2, "title": "18.2 Phase two, 2–5 years" },
   { "anchor": "s18-2-1", "level": 3, "title": "18.2.1 Chain-anchored campaigns and the first commercial structure" },
   { "anchor": "s18-3", "level": 2, "title": "18.3 Phase three, 5–10 years" },
   { "anchor": "s18-3-1", "level": 3, "title": "18.3.1 Leadership-class compute and the fusion long game" },
   { "anchor": "s18-4", "level": 2, "title": "18.4 Gates, dependencies, kill criteria" },
   { "anchor": "s18-4-1", "level": 3, "title": "18.4.1 The anchoring rule and my kill criteria" },
  ]
 },
 {
  "id": "ch19",
  "number": 19,
  "title": "19. Partnership and the Compute Ladder",
  "part": 6,
  "partName": "The Program",
  "wordCount": 2688,
  "readingTime": 12,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s19-1", "level": 2, "title": "19.1 The compute ladder for a one-person venture" },
   { "anchor": "s19-1-1", "level": 3, "title": "19.1.1 Open bottom rungs: NSF ACCESS and EuroHPC AI Factories" },
   { "anchor": "s19-1-2", "level": 3, "title": "19.1.2 Middle rungs: ERCAP's SBIR pool and Director's Discretionary" },
   { "anchor": "s19-1-3", "level": 3, "title": "19.1.3 The gated top: ALCC and INCITE" },
   { "anchor": "s19-2", "level": 2, "title": "19.2 Partnership rungs" },
   { "anchor": "s19-2-1", "level": 3, "title": "19.2.1 The Genesis consortium and lab embedding" },
   { "anchor": "s19-3", "level": 2, "title": "19.3 Validation partnerships as currency" },
   { "anchor": "s19-3-1", "level": 3, "title": "19.3.1 Credibility infrastructure, sequenced first" },
   { "anchor": "s19-3-2", "level": 3, "title": "19.3.2 Society engagement: symposia and challenges, not attendance" },
   { "anchor": "s19-4", "level": 2, "title": "19.4 Commercialization reality without a business plan" },
   { "anchor": "s19-4-1", "level": 3, "title": "19.4.1 What buyers actually buy" },
   { "anchor": "s19-4-2", "level": 3, "title": "19.4.2 Model patterns and the open gap" },
   { "anchor": "s19-4-3", "level": 3, "title": "19.4.3 My first twelve months" },
  ]
 },
 {
  "id": "ch20",
  "number": 20,
  "title": "20. The Skeptic Register and Validation Doctrine",
  "part": 6,
  "partName": "The Program",
  "wordCount": 1951,
  "readingTime": 8,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s20-1", "level": 2, "title": "20.1 The strongest objections, steel-manned" },
   { "anchor": "s20-1-1", "level": 3, "title": "20.1.1 Seven claims that failed, and what each one costs me" },
   { "anchor": "s20-1-2", "level": 3, "title": "20.1.2 The objections that survive the case-by-case record" },
   { "anchor": "s20-1-3", "level": 3, "title": "20.1.3 Inward application: auditing my own nine classes" },
   { "anchor": "s20-2", "level": 2, "title": "20.2 The validation doctrine" },
   { "anchor": "s20-3", "level": 2, "title": "20.3 What would change my mind" },
  ]
 },
 {
  "id": "ch21",
  "number": 21,
  "title": "21. Risk",
  "part": 6,
  "partName": "The Program",
  "wordCount": 1230,
  "readingTime": 5,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
   { "anchor": "s21-1", "level": 2, "title": "21.1 Technical risk" },
   { "anchor": "s21-1-1", "level": 3, "title": "21.1.1 The fidelity ceiling and the many-species data wall" },
   { "anchor": "s21-2", "level": 2, "title": "21.2 Credibility and solo-execution risk" },
   { "anchor": "s21-2-1", "level": 3, "title": "21.2.1 Trust-by-association, and one failed prediction as an existential event" },
   { "anchor": "s21-3", "level": 2, "title": "21.3 Policy, compute, and time-gate risk" },
   { "anchor": "s21-3-1", "level": 3, "title": "21.3.1 Lapses, gates, and vanishing instruments" },
  ]
 },
 {
  "id": "ch22",
  "number": 22,
  "title": "22. Conclusion",
  "part": 6,
  "partName": "The Program",
  "wordCount": 699,
  "readingTime": 3,
  "sections": [
   { "anchor": "s22-1", "level": 2, "title": "22.1 The bet, restated" },
   { "anchor": "s22-2", "level": 2, "title": "22.2 What I do next" },
  ]
 },
 {
  "id": "ch23",
  "number": 23,
  "title": "Glossary",
  "part": 6,
  "partName": "The Program",
  "wordCount": 2052,
  "readingTime": 9,
  "sections": [
   { "anchor": "opener", "level": 2, "title": "" },
  ]
 },
]
